/**
 * @file
 *
 * @author Generated by spec2x
 * $Rev$
 * $Date$
 */
#ifndef BIM_RPGNODE_HPP
#define BIM_RPGNODE_HPP

#include "bi/model/BayesNode.hpp"
#include "bi/state/Coord.hpp"
#include "bi/cuda/cuda.hpp"
#include "bi/math/scalar.hpp"
#include "bi/misc/compile.hpp"

#ifdef USE_SSE
#include "bi/math/sse.hpp" // overloads of standard math functions
#endif

/**
 * \f\$rPg\f\$; 
 */
class RPgNode : public bi::BayesNode {
public:
  /**
   * Constructor.
   */
  RPgNode();
  

};

#include "bi/model/model.hpp"
#include "bi/traits/type_traits.hpp"
#include "bi/traits/dimension_traits.hpp"
#include "bi/traits/boundary_traits.hpp"
#include "bi/traits/random_traits.hpp"





IS_GAUSSIAN_VARIATE(RPgNode);
IS_R_NODE(RPgNode);

















#endif
